name: mentalist
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  riverpod_annotation: ^2.2.1
  flutter_riverpod: ^2.4.4
  http: ^1.2.2
  url_launcher: ^6.3.1
  google_sign_in: ^6.2.1
  table_calendar: ^3.0.9
  flutter_svg: ^2.2.3
  fl_chart: ^1.1.1
  logger: ^2.4.0
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.5

flutter:
  uses-material-design: true

  assets:
    - assets/Google.png
    - assets/logoadmin.svg

  fonts:
    - family: Poppins
      fonts:
        - asset: font/Poppins-Black/Poppins-Light.ttf
          weight: 900
        - asset: font/Poppins-Black/Poppins-Italic.ttf
          style: italic
